# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-06 18:12
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='N.I.T.')),
                ('nombre', models.CharField(max_length=255, verbose_name='Razon social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre comercial')),
                ('correo', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electronico')),
                ('telefono1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono 2')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('nombre_contacto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono de contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electronico del contacto')),
                ('celular_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular del contacto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
                ('logo', models.ImageField(upload_to='uploads/fotos/clientes/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, unique=True, verbose_name='Color')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='configuracion_talla_detpedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla_fk', models.CharField(max_length=50, verbose_name='Talla')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Configuracion talla pedido',
                'verbose_name_plural': 'Configuracion tallas pedidos',
            },
        ),
        migrations.CreateModel(
            name='Control_MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gastada', models.PositiveIntegerField(verbose_name='Cantidad Gastada')),
                ('stock', models.PositiveIntegerField(verbose_name='Cantidad en Stock')),
            ],
            options={
                'verbose_name': 'Control Materia Prima',
                'verbose_name_plural': 'Control de Materia Prima',
            },
        ),
        migrations.CreateModel(
            name='Control_Prendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad entregada')),
                ('cantidad_pendiente', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad para despacho')),
            ],
            options={
                'verbose_name': 'Control de Prendas',
                'verbose_name_plural': 'Control de Prendas',
            },
        ),
        migrations.CreateModel(
            name='Detalle_predido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(help_text='Codigo generado automaticamente', max_length=100, verbose_name='Codigo del Pedido')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/pedidos/logos', verbose_name='Logo')),
                ('diseno', models.ImageField(upload_to='uploads/pedidos/dise\xf1o_prenda', verbose_name='Dise\xf1o de prenda')),
                ('tipo_logo', models.CharField(blank=True, choices=[('estampado', 'Estampado'), ('bordado', 'Bordado')], max_length=20, null=True, verbose_name='Tipo de logo')),
                ('ubicacion_logo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion del logo')),
                ('reflectivo', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=100, null=True, verbose_name='Reflectivo')),
                ('ubicacion_reflectivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion reflectivo')),
                ('observaciones_pedido', models.TextField(blank=True, null=True, verbose_name='Observaciones del pedido')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('encorte', 'En Corte'), ('enconfeccion', 'En Confeccion'), ('endisenologo', 'En Dise\xf1o de Logo'), ('despachado', 'Despachado')], max_length=100, verbose_name='Estado')),
                ('fecha_en_corte_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio corte')),
                ('fecha_en_corte_fin', models.DateField(blank=True, null=True, verbose_name='Fecha finalizacion corte')),
                ('fecha_en_confeccion_incio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio confeccion')),
                ('fecha_en_confeccion_fin', models.DateField(blank=True, null=True, verbose_name='Fecha finalizacion confeccion')),
                ('fecha_en_diseno_logo_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio dise\xf1o de logo')),
                ('fecha_en_diseno_logo_fin', models.DateField(blank=True, null=True, verbose_name='Fecha finalizacion dise\xf1o de logo')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones para correccion del pedido', null=True, verbose_name='Observaciones')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('cant_asig_mp', models.DecimalField(blank=True, decimal_places=0, default=Decimal('0.00'), max_digits=100, null=True, verbose_name='Cantidad de tela asignada (m)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Factura_CompraMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(verbose_name='Fecha de compra')),
                ('numeroFacturaMP', models.CharField(max_length=200, unique=True, verbose_name='Numero de Factura')),
                ('precio', models.DecimalField(decimal_places=0, help_text='Precio de compra por metro', max_digits=100, verbose_name='Precio de compra')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('descuento', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
            },
        ),
        migrations.CreateModel(
            name='Ficha_tecnica_detalle_confeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dotacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dotacion')),
                ('pes_puntes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pespuntes')),
                ('ojales', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ojales')),
                ('bolsillo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bolsillo')),
                ('sobrehilo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sobrehilo')),
                ('puntadas', models.CharField(blank=True, max_length=200, null=True, verbose_name='Puntadas')),
                ('color_hilo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Color de hilo')),
                ('dobladillos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dobladillos')),
                ('amarres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Amarres')),
                ('recubridora', models.CharField(blank=True, max_length=200, null=True, verbose_name='Recubridora')),
                ('bies', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bies')),
                ('color_recubridora', models.CharField(blank=True, max_length=200, null=True, verbose_name='Color')),
                ('entre_tela', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entretela')),
                ('tono', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle de confeccion',
                'verbose_name_plural': 'Detalle de confecciones',
            },
        ),
        migrations.CreateModel(
            name='Ficha_tecnica_detalle_costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoCorte', models.DecimalField(blank=True, decimal_places=0, help_text='en mano de Obra (Unitario)', max_digits=100, null=True, verbose_name='Costo de Corte')),
                ('costoConfeccion', models.DecimalField(blank=True, decimal_places=0, help_text='en mano de Obra (Unitario)', max_digits=100, null=True, verbose_name='Costo de Confeccion')),
                ('costologo', models.DecimalField(blank=True, decimal_places=0, help_text='en mano de Obra (Unitario)', max_digits=100, null=True, verbose_name='Costo de dise\xf1o de logo')),
                ('costoFlete', models.DecimalField(blank=True, decimal_places=0, help_text='en mano de Obra (Unitario)', max_digits=100, null=True, verbose_name='Costo de flete')),
                ('costoMateriaPrima', models.DecimalField(blank=True, decimal_places=0, help_text='en mano de Obra (Unitario)', max_digits=100, null=True, verbose_name='Costo materia prima')),
                ('costoAdicional', models.DecimalField(blank=True, decimal_places=0, help_text='en mano de Obra (Unitario)', max_digits=100, null=True, verbose_name='Costos adicionales')),
                ('costoFleteEntrada', models.DecimalField(blank=True, decimal_places=0, help_text='en mano de Obra (Unitario)', max_digits=100, null=True, verbose_name='Costo de flete en entrada')),
                ('costoFleteDespacho', models.DecimalField(blank=True, decimal_places=0, help_text='en mano de Obra (Unitario)', max_digits=100, null=True, verbose_name='Costo de flete para despacho')),
                ('descripcioncostoAdicional', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion de Costos Adicionales')),
                ('total_prenda', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True, verbose_name='Costo total por prenda')),
                ('total_pedido', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True, verbose_name='Costo total por pedido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle de costo',
                'verbose_name_plural': 'Detalle de costos',
            },
        ),
        migrations.CreateModel(
            name='Ficha_tecnica_detalle_insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Botones')),
                ('zipper', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zipper')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicacion Bolsillo')),
                ('remaches', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remaches')),
                ('elastico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Elastico')),
                ('ubicacion_remache', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicacion Remache')),
                ('tallin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tallin')),
                ('garra', models.CharField(blank=True, max_length=200, null=True, verbose_name='Garra')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle de insumo',
                'verbose_name_plural': 'Detalle de insumos',
            },
        ),
        migrations.CreateModel(
            name='Inventario_materia_prima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Inventario de materia prima',
                'verbose_name_plural': 'Inventario de materias primas',
            },
        ),
        migrations.CreateModel(
            name='Inventario_Prendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=200, verbose_name='Talla')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Inventario de Prendas',
                'verbose_name_plural': 'Inventario de Prendas',
            },
        ),
        migrations.CreateModel(
            name='materia_prima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Materia prima')),
                ('composicion', models.TextField(blank=True, null=True, verbose_name='Composicion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
            },
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pedido', models.PositiveIntegerField(unique=True, verbose_name='Orden de compra')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('aceptado', 'Aceptado')], max_length=20, verbose_name='Estado del pedido')),
                ('fecha_llegada', models.DateField(verbose_name='Fecha Llegada')),
                ('fechaEstimada_entrega', models.DateField(verbose_name='Fecha estimada para entrega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
                ('cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.clientes', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Odenes de compra',
            },
        ),
        migrations.CreateModel(
            name='prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prenda', models.CharField(max_length=200, verbose_name='Tipo prenda')),
                ('promedio_tela', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Promedio en tela')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
            },
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_proveedor', models.CharField(max_length=50, unique=True, verbose_name='N.I.T.')),
                ('nombre_proveedor', models.CharField(max_length=255, verbose_name='Proveedor')),
                ('encargado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jefe de area')),
                ('correo_proveedor', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electronico')),
                ('telefono1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono 2')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('contacto_proveedor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono de contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electronico del contacto')),
                ('celular_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular del contacto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
                ('municipio_fk', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='nuw_departamento_fk', chained_model_field='departamento_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.municipio', verbose_name='Municipio')),
                ('nuw_departamento_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del taller')),
                ('correo', models.EmailField(max_length=255, verbose_name='Correo Electronico')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('nombre_contacto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono de contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electronico del contacto')),
                ('celular_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular del contacto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion')),
                ('municipio_fk', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='nuw_departamento_fk', chained_model_field='departamento_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.municipio', verbose_name='Municipio')),
                ('nuw_departamento_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
    ]
