# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-06 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacion', '0001_initial'),
        ('prendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='digitador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='inventario_prendas',
            name='inventarioColor_fk',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='inventarioMP_fk', chained_model_field='materia_prima_fk', on_delete=django.db.models.deletion.CASCADE, to='prendas.color', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='inventario_prendas',
            name='inventarioMP_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.materia_prima', verbose_name='Materia Prima'),
        ),
        migrations.AddField(
            model_name='inventario_prendas',
            name='inventarioPrenda_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.prenda', verbose_name='Prenda'),
        ),
        migrations.AddField(
            model_name='inventario_materia_prima',
            name='color_fk',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='materia_prima_fk', chained_model_field='materia_prima_fk', on_delete=django.db.models.deletion.CASCADE, to='prendas.color', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='inventario_materia_prima',
            name='materia_prima_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.materia_prima', verbose_name='Materia prima'),
        ),
        migrations.AddField(
            model_name='ficha_tecnica_detalle_insumo',
            name='detalle_pedido_fk',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pedido_fk', chained_model_field='pedido', on_delete=django.db.models.deletion.CASCADE, to='prendas.Detalle_predido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='ficha_tecnica_detalle_insumo',
            name='pedido_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='ficha_tecnica_detalle_costo',
            name='detalle_pedido_fk',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pedido_fk', chained_model_field='pedido', on_delete=django.db.models.deletion.CASCADE, to='prendas.Detalle_predido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='ficha_tecnica_detalle_costo',
            name='pedido_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='ficha_tecnica_detalle_confeccion',
            name='detalle_pedido_fk',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pedido_fk', chained_model_field='pedido', on_delete=django.db.models.deletion.CASCADE, to='prendas.Detalle_predido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='ficha_tecnica_detalle_confeccion',
            name='pedido_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='factura_compramp',
            name='facturaMP_Color_fk',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='facturaMP_fk', chained_model_field='materia_prima_fk', on_delete=django.db.models.deletion.CASCADE, to='prendas.color', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='factura_compramp',
            name='facturaMP_fk',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='prendas.materia_prima', verbose_name='Materia Prima'),
        ),
        migrations.AddField(
            model_name='factura_compramp',
            name='proveedor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.proveedores', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='detalle_predido',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.color', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='detalle_predido',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.materia_prima', verbose_name='Materia prima'),
        ),
        migrations.AddField(
            model_name='detalle_predido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='detalle_predido',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.prenda', verbose_name='Prenda'),
        ),
        migrations.AddField(
            model_name='control_prendas',
            name='controlMP_Detallepedido_fk',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='controlMP_ordenC_fk', chained_model_field='pedido', on_delete=django.db.models.deletion.CASCADE, to='prendas.Detalle_predido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='control_prendas',
            name='controlMP_cliente_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.clientes', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='control_prendas',
            name='controlMP_ordenC_fk',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='controlMP_cliente_fk', chained_model_field='cliente_fk', on_delete=django.db.models.deletion.CASCADE, to='prendas.pedido', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='control_prendas',
            name='talla',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='controlMP_Detallepedido_fk', chained_model_field='detalle_pedido_fk', on_delete=django.db.models.deletion.CASCADE, to='prendas.configuracion_talla_detpedido', verbose_name='Talla'),
        ),
        migrations.AddField(
            model_name='control_materiaprima',
            name='FacturaCompraMP_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.Factura_CompraMP', verbose_name='Factura de Compra'),
        ),
        migrations.AddField(
            model_name='control_materiaprima',
            name='detallePedidoMP_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.Detalle_predido', verbose_name='Pedido al que pertenece'),
        ),
        migrations.AddField(
            model_name='configuracion_talla_detpedido',
            name='detalle_pedido_fk',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pedido_fk', chained_model_field='pedido', on_delete=django.db.models.deletion.CASCADE, to='prendas.Detalle_predido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='configuracion_talla_detpedido',
            name='pedido_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='configuracion_talla_detpedido',
            name='taller_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prendas.Taller', verbose_name='Taller'),
        ),
        migrations.AddField(
            model_name='color',
            name='materia_prima_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.materia_prima', verbose_name='Materia prima'),
        ),
        migrations.AddField(
            model_name='color',
            name='proveedor_fk',
            field=models.ManyToManyField(to='prendas.proveedores', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='municipio_fk',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='nuw_departamento_fk', chained_model_field='departamento_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nuw_departamento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.departamento', verbose_name='Departamento'),
        ),
    ]
