# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0002_auto_20181106_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/fotos/clientes/', verbose_name='Logo'),
        ),
    ]
