# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0003_auto_20181107_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_predido',
            name='diseno',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/pedidos/dise\xf1o_prenda', verbose_name='Dise\xf1o de prenda'),
        ),
    ]
