# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-23 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0004_auto_20181113_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_predido',
            name='modelo_orden',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pedidos/ordenes', verbose_name='modelo de orden'),
        ),
    ]
