# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-26 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0006_auto_20181126_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia_prima',
            name='codigo',
            field=models.CharField(default=1, max_length=150, verbose_name='Codigo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenda',
            name='codigo',
            field=models.CharField(default=1, max_length=150, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
