# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0007_auto_20181126_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia_prima',
            old_name='codigo',
            new_name='codigoMP',
        ),
        migrations.RenameField(
            model_name='prenda',
            old_name='codigo',
            new_name='codigoPrenda',
        ),
    ]
