# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0008_auto_20181127_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_compramp',
            name='fecha_compra',
            field=models.DateField(verbose_name='Fecha de compra'),
        ),
    ]
