# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-01 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0010_remove_color_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tallaje',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pedidos/tallajes', verbose_name='Tallaje'),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Materia prima'),
        ),
    ]
