# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-01 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0013_auto_20181201_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Color'),
        ),
    ]
