# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0015_auto_20181201_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_prima',
            name='codigoMP',
            field=models.CharField(max_length=150, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='codigoPrenda',
            field=models.CharField(max_length=150, unique=True, verbose_name='Codigo'),
        ),
    ]
