# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0016_auto_20181201_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='tipo_prenda',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tipo prenda'),
        ),
    ]
