# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0017_auto_20181201_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_predido',
            name='promedioPrenda',
            field=models.TextField(default=1, verbose_name='Promedio de Prenda'),
            preserve_default=False,
        ),
    ]
