# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-01 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0018_detalle_predido_promedioprenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_predido',
            name='promedioPrenda',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Promedio de prenda'),
        ),
    ]
