# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-08 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0019_auto_20181201_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='promedio_tela',
        ),
        migrations.AddField(
            model_name='color',
            name='codigoColor',
            field=models.CharField(default=0, max_length=100, verbose_name='Codigo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Materia prima'),
        ),
    ]
